name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: g++ ./main.cc -o main
    - name: check
      run: ls > list
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: main
        path: ./main
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: list
        path: ./list
