name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: g++ ./OI-Code.cpp -o OI-Code
    - name: mv
      run: cp ./OI-Code /usr/local/bin
